import { NestFactory } from '@nestjs/core';
import { AppModule } from '../app.module';
import { getModelToken } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Stock } from '../stocks/schemas/stocks.schema';
import { News } from '../news/schemas/news.schema';
import * as dotenv from 'dotenv';

dotenv.config();

export const COMPLETED_NEWS_ITEMS_11_15 = [
  {
    sequence: 11,
    headline: 'Unexplained Sub-Surface Electromagnetic Pulse Fries Regional Telecommunications and Fiber-Optic Hubs.',
    desc: 'A rogue underground energy discharge sends a localized electromagnetic shockwave through financial and commercial sectors. Cloud servers and online-only databases suffer catastrophic memory wipes, crippling firms dependent on live internet connections.',
    effectsMap: { KIC: 1700, ACS: 610, ASB: 2150 },
  },
  {
    sequence: 12,
    headline: 'Raw Iron and Coal Deposits Across Subterranean Mines Found to Be Magnetically Charged by Sub-Surface Anomaly.',
    desc: 'Miners underground report that extracted raw iron and coal are spontaneously developing intense magnetic fields. While traditional steel mills reject the anomalous ore, specialized defense contractors discover the material blocks electromagnetic interference naturally.',
    effectsMap: { SSM: 830, K333: 650, NAS: 1670 },
  },
  {
    sequence: 13,
    headline: 'Smart-Vehicles Stalled Nationwide as Onboard Computers Reject Severe Atmospheric Magnetic Shifts.',
    desc: 'Millions of consumer electric and smart vehicles simultaneously shut down on highways and city streets as their microprocessors register unhandled electromagnetic distortion. Dealerships and consumer manufacturers face an unprecedented wave of paralyzed vehicle liability.',
    effectsMap: { MUB: 1290, AYN: 300, MLH: 220 },
  },
  {
    sequence: 14,
    headline: 'Emergency Architectural Codes Mandate Faraday-Cage and Copper-Mesh Smart Concrete Siding for All Commercial Towers.',
    desc: 'Following the electromagnetic pulse event, city councils pass rigorous building code revisions requiring all standing structures to be shielded against future radiation and magnetic waves. Property owners scramble to retrofit existing high-rises.',
    effectsMap: { OMER: 920, BURR: 450, IAR: 1090 },
  },
  {
    sequence: 15,
    headline: 'Gold-Plated Circuitry Melts Under Intense New Atmospheric Ionization Frequencies and Frequency Spikes.',
    desc: 'The shifting atmospheric frequency causes standard gold-plated electronic connections in industrial machinery to instantly superheat and liquefy. Factories face widespread hardware meltdowns, requiring massive quantities of alternative alloys to re-wire critical systems.',
    effectsMap: { ZSG: 2150, ASB: 1900, SAB: 1490 },
  },
];

export const DUMMY_TEST_NEWS_ITEMS = [
  {
    sequence: 15.1,
    headline: '[TEST DUMMY 1] Diagnostic Signal Calibration',
    desc: 'Temporary test announcement to verify live market feed and automated scheduling. Will be deleted before Day 2 starts.',
    effectsMap: { KIC: 1850, ACS: 750, SAB: 1350 },
  },
  {
    sequence: 15.2,
    headline: '[TEST DUMMY 2] Sub-System Frequency Verification',
    desc: 'Secondary trial headline to test multi-asset price adjustment and queue transition. Will be deleted before Day 2 starts.',
    effectsMap: { GFE: 1450, NAS: 1520, BURR: 520 },
  },
];

export const QUEUED_NEWS_ITEMS = [
  {
    sequence: 16,
    headline: 'Deep Geothermal Power Stations Successfully Tap Sub-Surface Heat Generated by the Particle Accelerator Anomaly.',
    desc: 'While traditional power grids struggle, clean energy pioneers successfully drill into the thermal fault lines caused by the underground physics anomaly. This yields an endless, highly concentrated geothermal energy source that bypasses conventional grid vulnerabilities.',
    effectsMap: { GFE: 1550, NAS: 1390, K333: 720 },
  },
  {
    sequence: 17,
    headline: 'Laboratory Test Subjects Exposed to Radiation Anomaly Exhibit Rapid, Unpredictable Cellular Adaptation.',
    desc: 'Containment facilities studying the bio-vector report that ambient radiation is accelerating the pathogen\'s mutation rate, causing structural containment failures and forcing research teams to deploy heavy radiation-hardened observation shields.',
    effectsMap: { IAR: 1270, NLB: 920, ABG: 560 },
  },
  {
    sequence: 18,
    headline: 'Digital Transaction Ledgers Corrupted Beyond Repair; Authorities Force Temporary Return to Physical Paper Assets.',
    desc: 'The cumulative effect of electromagnetic interference and server crashes corrupts core interbank digital clearing ledgers. To prevent total commercial paralysis, banking regulators order institutions to revert to physical paper-ledger settlements for all trade.',
    effectsMap: { SAB: 1800, ABG: 210, KIC: 1820 },
  },
  {
    sequence: 19,
    headline: 'Crops Exposed to Ionized Air Exhibit 300% Growth Velocity but Disastrous Chemical Toxicity Profiles.',
    desc: 'Farms caught in the atmospheric ionization path experience explosive plant growth, but agricultural testing reveals the harvested grain is heavily laced with mutagenic toxins, rendering it entirely unfit for human consumption.',
    effectsMap: { MLH: 70, GFE: 1650, BURR: 410 },
  },
  {
    sequence: 20,
    headline: 'Data Center Cooling Towers Flash-Freeze Due to Sudden Atmospheric Temperature Plunges and Ion Storms.',
    desc: 'A freak weather front driven by the upper-atmospheric anomaly causes ambient temperatures around primary cloud server farms to plummet instantly. Water-cooling towers freeze solid, threatening catastrophic hardware meltdowns across major data networks.',
    effectsMap: { KIC: 2070, ACS: 410, ZSG: 2240 },
  },
];

export async function seedQueuedNews(appContext?: any) {
  let app = appContext;
  let createdApp = false;
  if (!app) {
    app = await NestFactory.createApplicationContext(AppModule);
    createdApp = true;
  }

  try {
    const stockModel: Model<Stock> = app.get(getModelToken(Stock.name));
    const newsModel: Model<News> = app.get(getModelToken(News.name));

    const existingStocks = await stockModel.find().exec();
    console.log(`[SeedQueuedNews] Found ${existingStocks.length} existing stocks in database.`);

    // Ensure 11..15 are marked released: true
    await newsModel.updateMany({ sequence: { $lte: 15 }, released: false }, { released: true }).exec();

    let addedCount = 0;
    let updatedCount = 0;
    const itemsToProcess = [...DUMMY_TEST_NEWS_ITEMS, ...QUEUED_NEWS_ITEMS];

    for (const item of itemsToProcess) {
      const existingNews = await newsModel.findOne({ sequence: item.sequence }).exec();

      if (existingNews) {
        // Update verbatim headline and desc if different
        existingNews.headline = item.headline;
        existingNews.desc = item.desc;
        await existingNews.save();
        updatedCount++;
        console.log(`[SeedQueuedNews] Sequence #${item.sequence} updated with verbatim headline and desc.`);
        continue;
      }

      const effects = existingStocks.map((stock) => {
        const stockName = stock.name || '';
        let matchedPrice = -1;

        for (const [ticker, price] of Object.entries(item.effectsMap)) {
          if (stockName.startsWith(ticker + ' ') || stockName.includes(ticker)) {
            matchedPrice = price;
            break;
          }
        }

        return {
          id: String(stock._id),
          newBuy: matchedPrice,
        };
      });

      await newsModel.create({
        sequence: item.sequence,
        headline: item.headline,
        desc: item.desc,
        effects,
        released: false,
      });

      addedCount++;
      console.log(`[SeedQueuedNews] Queued news #${item.sequence} created successfully.`);
    }

    console.log(`[SeedQueuedNews] Finished! Added ${addedCount}, updated ${updatedCount} queued news items.`);
    return { success: true, addedCount, updatedCount };
  } finally {
    if (createdApp && app) {
      await app.close();
    }
  }
}

if (require.main === module) {
  seedQueuedNews()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('[SeedQueuedNews] Error seeding queued news:', err);
      process.exit(1);
    });
}
